module.exports = {
  CACHE: {
    KEY: {
      DEXASSETLIST: 'DEXASSETLIST',
      DEXDASHBOARD: 'DEXDASHBOARD',
      CROSSCHAINLIST: 'CROSSCHAINLIST',
      UNIONLIST: 'UNIONLIST',
      ACCUMULATEDTXAMOUNT: 'ACCUMULATEDTXAMOUNT',
      TOTALUSERSTAT: 'TOTALUSERSTAT',
      TOTALTRADESTAT: 'TOTALTRADESTAT',
    },
  },
};
